package com.apenkovsky.enums;

public enum EmailTemplate {
    FEEDBACK_WAS_PROVIDED,
    NEW_TICKET_FOR_APPROVAL,
    TICKET_WAS_APPROVED,
    TICKET_WAS_CANCELLED_BY_ENGINEER,
    TICKET_WAS_CANCELLED_BY_MANAGER,
    TICKET_WAS_DECLINED,
    TICKET_WAS_DONE

}
